name: hypetro
description: An opinionated UI layer framework. Created to use with flutter_bloc.
version: 0.0.1
repository: https://github.com/Luckey-Elijah/hypetro
issue_tracker: https://github.com/Luckey-Elijah/hypetro/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^7.3.1
  meta: ^1.7.0

dev_dependencies:
  bloc_test: ^8.3.0
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

  mockito: ^5.0.16
  very_good_analysis: ^2.3.0

flutter:
